networks:
  t4y:
    external: true

services:
  # 실시간 10대의 운행정보
  driverlogmain:
    image: openjdk:11-jre
    container_name: smartcar-loggen-realtime
    volumes:
      - ./smart-car/bigdata.smartcar.loggen-1.0.jar:/app.jar
      - ./smart-car/driver-realtime-log:/driver-realtime-log
    command: >
      java -DlogFilename=/driver-realtime-log/SmartCarDriverInfo.log 
           -cp /app.jar com.wikibook.bigdata.smartcar.loggen.DriverLogMain ${TODAY_DATE} 10
    networks:
      - t4y
    depends_on:
      - fluent-bit1
  
  # DriverLogMain Collector
  fluent-bit1:
    image: fluent/fluent-bit:latest
    container_name: fluent-bit1
    volumes:
      - ./fluent-bit/streaming/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./fluent-bit/streaming/parsers.conf:/fluent-bit/etc/parsers.conf
      - ./smart-car/driver-realtime-log:/var/log
    ports:
      - "2020:2020"
    restart: always
    networks:
      - t4y
